### ISSUE TITLE
deprecation API warning

### ISSUE THREAD

**Issue by ruthvik-github** [jaumard/sms_autofill#48]
i am having latest version in pubspec.yaml
<img width="230" alt="Screenshot 2020-07-30 at 9 10 17 PM" src="https://user-images.githubusercontent.com/64551464/88943426-144b3300-d2a9-11ea-9649-d9252924c60b.png">

and i am getting this warning some times
<img width="932" alt="Screenshot 2020-07-30 at 9 09 21 PM" src="https://user-images.githubusercontent.com/64551464/88943504-31800180-d2a9-11ea-8b66-ac8b1f913bfd.png">

how can i change the code to avoid such errors.

**Comment by jaumard** [comment]
Would be nice to know which API causes problem, it probably need to be change inside the plugin

**Comment by jaumard** [comment]
Should be fixed in 1.2.6 thanks to @jack24254029

**Comment by jack24254029** [comment]
```
Note: /root/.pub-cache/hosted/pub.dartlang.org/sms_autofill-1.2.6/android/src/main/java/com/jaumard/smsautofill/AppSignatureHelper.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
```

`1.2.6` still have some deprecated APIs, but I am not sure which API is deprecated.

**Comment by ruthvik-github** [comment]
```
sms_autofill-8aa82ffe539d2289951511af8257ea97e9e2b80d/android/src/main/java/com/jaumard/smsautofill/AppSignatureHelper.java:59: warning: [deprecation] GET_SIGNATURES in PackageManager has been deprecated
                    PackageManager.GET_SIGNATURES).signatures;
                                  ^
git/sms_autofill-8aa82ffe539d2289951511af8257ea97e9e2b80d/android/src/main/java/com/jaumard/smsautofill/AppSignatureHelper.java:59: warning: [deprecation] signatures in PackageInfo has been deprecated
                    PackageManager.GET_SIGNATURES).signatures;
```

**Comment by ruthvik-github** [comment]
I am getting these Warnings even after updating packages
 ```
pawanv/development/flutter/.pub-cache/git/sms_autofill-8aa82ffe539d2289951511af8257ea97e9e2b80d/android/src/main/java/com/jaumard/smsautofill/AppSignatureHelper.java:59: warning: [deprecation] GET_SIGNATURES in PackageManager has been deprecated
                    PackageManager.GET_SIGNATURES).signatures;
                                  ^
flutter/.pub-cache/git/sms_autofill-8aa82ffe539d2289951511af8257ea97e9e2b80d/android/src/main/java/com/jaumard/smsautofill/AppSignatureHelper.java:59: warning: [deprecation] signatures in PackageInfo has been deprecated
                    PackageManager.GET_SIGNATURES).signatures;
                                                  ^
2 warnings
```
i have updated dependencies as well

**Comment by Amr1440** [comment]
still getting same error using 
sms_autofill: ^2.0.1
<img width="1843" alt="Screen Shot 2021-09-08 at 10 55 41 AM" src="https://user-images.githubusercontent.com/52917852/132469671-5ae6ebe0-ee0b-4826-b1bd-6977acade7b4.png">
@jaumard
